# Generated by Django 3.0.4 on 2021-03-18 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210313_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='image_class',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
