# Generated by Django 3.0.4 on 2021-03-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_file_image_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image_class',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='labels',
            field=models.TextField(blank=True, default=''),
        ),
    ]
